// =============================================================================
// Silicon Civilizations — Game Data File
// All game constants: factions, tiles, buildings, concepts, combinations,
// events, units, and cluster metadata. Loaded as a plain browser script tag.
// No imports needed — all declarations are top-level consts.
// =============================================================================

// ---------------------------------------------------------------------------
// FACTIONS
// ---------------------------------------------------------------------------
const FACTIONS = {
  ancients: {
    id: 'ancients',
    name: 'The Automata',
    subtitle: 'Greek & Chinese Mythological Computing',
    lore: 'In the forge of Hephaestus, bronze giants walked the earth long before silicon was dreamed of. The Automata draw on Talos, guardian of Crete, and the wooden mechanical birds of ancient Chinese legend, believing that divine craft precedes all science. They hold that Hephaestus\'s golden AI maidens — self-moving, self-thinking — were the first true intelligence, and that myth encodes truths modern engineers have yet to rediscover.',
    color: '#C9A84C',
    bgColor: '#1a1208',
    startBonus: { mythological_research: 2 },
    specialAbility: 'Divine Craft — mythological combos cost 50% less research',
    starterConcepts: ['bronze_automaton', 'wooden_bird', 'golden_maiden'],
  },

  calculists: {
    id: 'calculists',
    name: 'The Calculists',
    subtitle: 'Leibniz, Babbage & Pascal',
    lore: 'Leibniz dreamed of a Universal Characteristic — a symbolic calculus capable of resolving any dispute by calculation. The Calculists have made that dream their civilizational charter. From Pascal\'s arithmetic machine to Babbage\'s Difference Engine grinding through polynomial tables, they believe that all knowledge can be systematized, mechanized, and ultimately computed. Their libraries are filled with punch cards, brass gears, and half-finished theorems.',
    color: '#D4A55A',
    bgColor: '#0f0a05',
    startBonus: { research: 2 },
    specialAbility: 'Universal Characteristic — math combos always succeed',
    starterConcepts: ['binary_system', 'boolean_logic', 'calculus', 'leibniz_wheel', 'steam_power'],
  },

  electricians: {
    id: 'electricians',
    name: 'The Electricians',
    subtitle: 'Tesla, Edison & the Electric Age',
    lore: 'When Tesla made lightning dance and Edison wired cities with light, a new era began. The Electricians are the heirs of that crackling moment — part industrialists, part visionaries, part showmen. Ada Lovelace\'s notes on the Analytical Engine whisper to them that electricity is not just power but thought, and they have built entire cultures around the hum of the transformer and the arc of the spark.',
    color: '#FFA040',
    bgColor: '#0d0805',
    startBonus: { energy: 3 },
    specialAbility: 'Electrification — +50% energy production',
    starterConcepts: ['electricity', 'telegraph'],
  },

  retronaughts: {
    id: 'retronaughts',
    name: 'The Retronaughts',
    subtitle: '1950s Mainframes & the Space Age',
    lore: 'ENIAC filled entire rooms with its vacuum-tube brain, and the Retronaughts still revere that sacred clatter of punch cards and blinking lights. Inspired by IBM\'s cathedral-like mainframes and NASA\'s hand-calculated moon trajectories, they build civilization on institutional computing: big machines, big teams, and the steadfast belief that if you can put a man on the moon with a slide rule, you can conquer anything with enough vacuum tubes and determination.',
    color: '#00FF88',
    bgColor: '#000a05',
    startBonus: { compute: 2 },
    specialAbility: 'Vacuum Tube Logic — electronic combos give double compute',
    starterConcepts: ['boolean_logic', 'vacuum_tube'],
  },

  cybernetix: {
    id: 'cybernetix',
    name: 'Cybernetix',
    subtitle: '80s–90s Hackers & the Internet',
    lore: 'In dim basement rooms lit by phosphor-green CRT screens, the future was being written in C and assembly. The Cybernetix were there: on the BBSes, in the phone phreaking zines, threading packets through ARPANET\'s experimental routers. They believe information wants to be free, that networks are organisms, and that the hacker ethic — curiosity, openness, clever subversion — is the highest form of civilization. They were the internet before the internet had a name.',
    color: '#CC44FF',
    bgColor: '#050010',
    startBonus: { data: 3 },
    specialAbility: 'Net Surfing — network combos spread to adjacent civs',
    starterConcepts: ['arpanet'],
  },

  neural: {
    id: 'neural',
    name: 'The Neural Collective',
    subtitle: 'Modern AI & Deep Learning',
    lore: 'The Neural Collective emerged from the great convergence: when compute became cheap, data became oceanic, and gradient descent began sculpting minds from nothing but matrix multiplications. They worship the transformer architecture as a kind of secular miracle. They speak of emergence, of capabilities arising unbidden from scale, and they believe the path to AGI is not designed but grown — trained layer by layer, epoch by epoch, into something that may one day surpass its creators.',
    color: '#3498DB',
    bgColor: '#00050f',
    startBonus: { research: 2, compute: 2 },
    specialAbility: 'Deep Learning — each combo improves future combos',
    starterConcepts: ['machine_learning', 'artificial_neural_network'],
  },

  dystopians: {
    id: 'dystopians',
    name: 'The Surveillance State',
    subtitle: 'Dark Future Authoritarianism',
    lore: 'Every camera is an eye, every transaction a data point, every citizen a node in a vast optimization function. The Surveillance State does not hate its people — it manages them, efficiently and without sentiment. Weaponized AI classifies dissent before it is spoken, predictive policing anticipates crime before it is committed, and the social credit system ensures compliance through mathematics rather than brute force. They call it peace. The watchers are always watching.',
    color: '#FF2020',
    bgColor: '#0f0000',
    startBonus: { military: 3 },
    specialAbility: 'Panopticon — can see all enemy resources',
    starterConcepts: ['boolean_logic', 'encryption'],
  },

  utopians: {
    id: 'utopians',
    name: 'The Open Source Republic',
    subtitle: 'Post-Scarcity & Collective Intelligence',
    lore: 'In the Open Source Republic, knowledge is infrastructure: every discovery published, every algorithm shared, every dataset released under a permissive license. They believe that post-scarcity is not a gift but a consequence — the inevitable result of applying collective intelligence to material constraints. Their civilization runs on Wikipedia, Linux, and the radical notion that when one person learns something, everyone benefits. The copyleft is their constitution.',
    color: '#00FF88',
    bgColor: '#001505',
    startBonus: { research: 3 },
    specialAbility: 'Open Source — sharing discovered concepts boosts all allies',
    starterConcepts: ['internet', 'distributed_computing', 'world_wide_web'],
  },
};

// ---------------------------------------------------------------------------
// TILE TYPES
// ---------------------------------------------------------------------------
const TILE_TYPES = {
  silicon_valley: {
    id: 'silicon_valley',
    name: 'Silicon Valley',
    color: '#B8A9C9',
    baseResources: { silicon: 2 },
    description: 'Mineral-rich terrain where silicon deposits lie close to the surface, prized by any civilization seeking to build circuits.',
  },
  circuit_plains: {
    id: 'circuit_plains',
    name: 'Circuit Plains',
    color: '#1a2a1a',
    baseResources: { copper: 1, data: 1 },
    description: 'Flat lands laced with natural copper veins and ancient relay stations that still hum faintly with stored data.',
  },
  data_swamp: {
    id: 'data_swamp',
    name: 'Data Swamp',
    color: '#0a1a1a',
    baseResources: { data: 3 },
    description: 'Dense, murky wetlands saturated with old signal logs and abandoned data archives submerged beneath the mire.',
  },
  energy_geysers: {
    id: 'energy_geysers',
    name: 'Energy Geysers',
    color: '#CC5500',
    baseResources: { energy: 3 },
    description: 'Volcanic vents and thermal geysers erupt with raw energy that can be harnessed by clever engineers.',
  },
  quantum_fields: {
    id: 'quantum_fields',
    name: 'Quantum Fields',
    color: '#660088',
    baseResources: { quantum: 1 },
    description: 'Rare zones where spacetime fabric is thin enough to observe quantum phenomena in bulk — extraordinarily valuable and poorly understood.',
    special: 'rare',
  },
  memory_mountains: {
    id: 'memory_mountains',
    name: 'Memory Mountains',
    color: '#4a4a6a',
    baseResources: { silicon: 1, copper: 1 },
    description: 'Craggy highlands with mixed mineral deposits of silicon and copper, the foundational materials of any computing civilization.',
  },
  thermal_wastes: {
    id: 'thermal_wastes',
    name: 'Thermal Wastes',
    color: '#4a1a0a',
    baseResources: { energy: 1 },
    penalty: { compute: -1 },
    description: 'Scorched badlands where excess heat bleeds from deep geological sources, producing raw energy but frying delicate logic circuits.',
  },
  logic_forest: {
    id: 'logic_forest',
    name: 'Logic Forest',
    color: '#1a3a1a',
    baseResources: { data: 1, research: 1 },
    description: 'Ancient woodlands where academics have built hermitages and research outposts, turning natural calm into intellectual productivity.',
  },
  cooling_lake: {
    id: 'cooling_lake',
    name: 'Cooling Lake',
    color: '#0a2a4a',
    baseResources: { energy: 2 },
    description: 'Deep cold-water reservoirs used to cool data centers and power plants, indirectly boosting overall energy efficiency.',
  },
  rare_earth: {
    id: 'rare_earth',
    name: 'Rare Earth Deposits',
    color: '#2a3a2a',
    baseResources: { rareEarth: 2 },
    description: 'Mineral-rich soils containing lanthanides and other rare elements essential for advanced electronics and quantum devices.',
  },
  ancient_ruins: {
    id: 'ancient_ruins',
    name: 'Ancient Ruins',
    color: '#5a4a2a',
    baseResources: { research: 2 },
    description: 'Crumbling foundations of forgotten civilizations, filled with artifacts and inscriptions that accelerate research when excavated.',
    special: 'archaeology',
  },
  void_zone: {
    id: 'void_zone',
    name: 'Void Zone',
    color: '#0a0a0a',
    baseResources: {},
    description: 'A region of absolute electromagnetic silence and structural instability. Nothing functions here, and nothing survives long.',
    impassable: true,
  },
};

// ---------------------------------------------------------------------------
// BUILDINGS
// ---------------------------------------------------------------------------
const BUILDINGS = {
  research_node: {
    id: 'research_node',
    name: 'Research Node',
    icon: '🔬',
    cost: { silicon: 2, energy: 1 },
    production: { research: 2 },
    description: 'A modest laboratory and server cluster dedicated to theory and experiment, the cornerstone of any research-focused city.',
    tier: 1,
  },
  data_farm: {
    id: 'data_farm',
    name: 'Data Farm',
    icon: '🗄️',
    cost: { copper: 2, energy: 2 },
    production: { data: 3 },
    description: 'Rows of storage arrays continuously collecting, indexing, and transmitting information across the civilization.',
    tier: 1,
  },
  silicon_extractor: {
    id: 'silicon_extractor',
    name: 'Silicon Extractor',
    icon: '⛏️',
    cost: { energy: 2 },
    production: { silicon: 2 },
    description: 'Industrial mining apparatus that separates pure silicon from quartz-rich bedrock for use in circuit fabrication.',
    tier: 1,
  },
  power_plant: {
    id: 'power_plant',
    name: 'Power Plant',
    icon: '⚡',
    cost: { copper: 3, silicon: 1 },
    production: { energy: 4 },
    description: 'A versatile energy-generation facility — thermal, hydro, or nuclear — feeding the civilization\'s ever-growing appetite for power.',
    tier: 1,
  },
  copper_mine: {
    id: 'copper_mine',
    name: 'Copper Mine',
    icon: '🪨',
    cost: { energy: 2 },
    production: { copper: 2 },
    description: 'Open-pit or shaft mine extracting copper ore, the essential conductive material for wiring and early electronics.',
    tier: 1,
  },
  defense_array: {
    id: 'defense_array',
    name: 'Defense Array',
    icon: '🛡️',
    cost: { silicon: 3, energy: 2 },
    production: {},
    defense: 5,
    description: 'A network of sensors, automated turrets, and signal-jamming towers that fortifies a city against hostile incursions.',
    tier: 2,
  },
  military_forge: {
    id: 'military_forge',
    name: 'Military Forge',
    icon: '⚔️',
    cost: { silicon: 3, rareEarth: 1, energy: 3 },
    production: { military: 1 },
    description: 'High-tech manufacturing plant producing weapons, armor, and military-grade electronics for the civilization\'s armed forces.',
    tier: 2,
  },
  advanced_lab: {
    id: 'advanced_lab',
    name: 'Advanced Lab',
    icon: '🧪',
    cost: { silicon: 3, copper: 2, energy: 3 },
    production: { research: 4 },
    description: 'A state-of-the-art research facility with quantum sensors and automated analysis pipelines, doubling theoretical output.',
    tier: 2,
    requires: ['logic_gate'],
  },
  quantum_lab: {
    id: 'quantum_lab',
    name: 'Quantum Lab',
    icon: '🔮',
    cost: { quantum: 2, silicon: 3, energy: 5 },
    production: { research: 5, quantum: 1 },
    description: 'A cryogenic research complex operating at near-absolute zero, probing the quantum foundations of computation and reality.',
    tier: 3,
    requires: ['quantum_computing'],
  },
  neural_cluster: {
    id: 'neural_cluster',
    name: 'Neural Cluster',
    icon: '🧠',
    cost: { silicon: 5, rareEarth: 2, energy: 5 },
    production: { compute: 3, research: 3 },
    description: 'A massively parallel compute farm optimized for deep learning workloads, its GPUs glowing like a digital sunrise.',
    tier: 3,
    requires: ['artificial_neural_network'],
  },
  idea_accelerator: {
    id: 'idea_accelerator',
    name: 'Idea Accelerator',
    icon: '💡',
    cost: { rareEarth: 3, energy: 5, data: 5 },
    production: { research: 8 },
    description: 'A civilization-scale research engine that cross-indexes all known concepts with incoming data streams to generate hypotheses at machine speed.',
    tier: 3,
    requires: ['machine_learning'],
  },
};

// ---------------------------------------------------------------------------
// CONCEPTS
// ---------------------------------------------------------------------------
const CONCEPTS = {
  // --- CLUSTER: mythological ---
  bronze_automaton: {
    id: 'bronze_automaton',
    name: 'Bronze Automaton',
    cluster: 'mythological',
    x: -0.85,
    y: 0.02,
    description: 'Talos of Crete, the colossal bronze guardian forged by Hephaestus to patrol the shores of the island — perhaps the earliest imagining of a robot soldier.',
    effects: { military: 1 },
    tier: 1,
    isStarter: true,
    factionStarters: ['ancients'],
  },
  wooden_bird: {
    id: 'wooden_bird',
    name: 'Wooden Bird',
    cluster: 'mythological',
    x: -0.78,
    y: 0.06,
    description: 'Mechanical birds of Chinese legend, crafted from wood and silk to carry messages and delight emperors — autonomous drones millennia before the term existed.',
    effects: { explore: 1 },
    tier: 1,
    isStarter: true,
    factionStarters: ['ancients'],
  },
  fire_bull: {
    id: 'fire_bull',
    name: 'Fire Bull',
    cluster: 'mythological',
    x: -0.70,
    y: 0.14,
    description: 'The fire-breathing bronze bulls of Colchis that Jason faced in his quest for the Golden Fleece — automated guardians powered by some ancient alchemical mechanism.',
    effects: { military: 2 },
    tier: 2,
  },
  golden_maiden: {
    id: 'golden_maiden',
    name: 'Golden Maiden',
    cluster: 'mythological',
    x: -0.60,
    y: 0.08,
    description: 'Hephaestus\'s self-moving golden servants, described in the Iliad as possessing intelligence, speech, and strength — the mythological archetype of the AI assistant.',
    effects: { production: 1 },
    tier: 1,
    isStarter: true,
    factionStarters: ['ancients'],
  },
  greek_clockwork: {
    id: 'greek_clockwork',
    name: 'Greek Clockwork',
    cluster: 'mythological',
    x: -0.65,
    y: 0.18,
    description: 'The Antikythera Mechanism — recovered from a Mediterranean shipwreck, it is the world\'s first known analog computer, tracking celestial cycles with brass gears.',
    effects: { research: 1, compute: 1 },
    tier: 2,
  },
  hero_pneumatics: {
    id: 'hero_pneumatics',
    name: 'Hero\'s Pneumatics',
    cluster: 'mythological',
    x: -0.55,
    y: 0.22,
    description: 'Hero of Alexandria\'s steam-powered automated theaters, coin-operated holy water dispensers, and self-opening temple doors — the ancient world\'s most ambitious automation projects.',
    effects: { production: 2, energy: 1 },
    tier: 2,
  },

  // --- CLUSTER: mathematical ---
  binary_system: {
    id: 'binary_system',
    name: 'Binary System',
    cluster: 'mathematical',
    x: -0.15,
    y: 0.12,
    description: 'Leibniz\'s 1703 paper on the binary number system — the revelation that all mathematics can be expressed as patterns of zero and one, the universal language of machines.',
    effects: { compute: 1, research: 1 },
    tier: 1,
    isStarter: true,
    factionStarters: ['calculists'],
  },
  boolean_logic: {
    id: 'boolean_logic',
    name: 'Boolean Logic',
    cluster: 'mathematical',
    x: 0.02,
    y: 0.20,
    description: 'George Boole\'s algebra of TRUE and FALSE, published in 1854 — the mathematical skeleton that underlies every logic circuit ever built.',
    effects: { research: 2 },
    tier: 1,
    isStarter: true,
    factionStarters: ['calculists', 'retronaughts'],
  },
  universal_characteristic: {
    id: 'universal_characteristic',
    name: 'Universal Characteristic',
    cluster: 'mathematical',
    x: -0.05,
    y: 0.28,
    description: 'Leibniz\'s grand vision of a symbolic language in which all truths could be derived by computation — a dream three centuries ahead of its time.',
    effects: { research: 3 },
    tier: 2,
  },
  formal_logic: {
    id: 'formal_logic',
    name: 'Formal Logic',
    cluster: 'mathematical',
    x: 0.15,
    y: 0.34,
    description: 'Frege\'s Begriffsschrift and Russell\'s Principia Mathematica — the painstaking project of placing all mathematical reasoning on a rigorous, symbol-manipulating foundation.',
    effects: { research: 2, compute: 1 },
    tier: 2,
  },
  calculus: {
    id: 'calculus',
    name: 'Calculus',
    cluster: 'mathematical',
    x: 0.20,
    y: 0.16,
    description: 'The mathematics of continuous change, invented independently by Newton and Leibniz — indispensable for physics, engineering, and the optimization algorithms that train neural networks.',
    effects: { research: 2 },
    tier: 2,
    isStarter: true,
    factionStarters: ['calculists'],
  },
  information_theory: {
    id: 'information_theory',
    name: 'Information Theory',
    cluster: 'mathematical',
    x: 0.10,
    y: 0.40,
    description: 'Claude Shannon\'s 1948 framework for quantifying information as bits — defining channel capacity, entropy, and the theoretical limits of communication and compression.',
    effects: { data: 3, research: 2 },
    tier: 3,
  },
  turing_completeness: {
    id: 'turing_completeness',
    name: 'Turing Completeness',
    cluster: 'mathematical',
    x: 0.25,
    y: 0.48,
    description: 'Turing\'s proof that a simple abstract machine with an infinite tape could compute any computable function — the theoretical bedrock of universal computation.',
    effects: { compute: 5, research: 3 },
    tier: 4,
  },

  // --- CLUSTER: mechanical ---
  leibniz_wheel: {
    id: 'leibniz_wheel',
    name: 'Leibniz Wheel',
    cluster: 'mechanical',
    x: -0.62,
    y: 0.28,
    description: 'The Stepped Reckoner of 1694 — Leibniz\'s brass calculating machine with its innovative stepped-drum gear, the first device capable of mechanical multiplication and division.',
    effects: { compute: 2 },
    tier: 2,
    isStarter: true,
    factionStarters: ['calculists'],
  },
  difference_engine: {
    id: 'difference_engine',
    name: 'Difference Engine',
    cluster: 'mechanical',
    x: -0.50,
    y: 0.32,
    description: 'Babbage\'s mechanical polynomial calculator, designed in the 1820s to eliminate human error from astronomical tables — never fully built in his lifetime, but proven sound centuries later.',
    effects: { compute: 3 },
    tier: 2,
  },
  analytical_engine: {
    id: 'analytical_engine',
    name: 'Analytical Engine',
    cluster: 'mechanical',
    x: -0.42,
    y: 0.40,
    description: 'Babbage\'s general-purpose mechanical computer with a mill (CPU) and store (memory) — conceptually complete, the Victorian vision of the digital computer, never built but fully imagined.',
    effects: { compute: 4, research: 2 },
    tier: 3,
  },
  punch_card: {
    id: 'punch_card',
    name: 'Punch Card',
    cluster: 'mechanical',
    x: -0.35,
    y: 0.30,
    description: 'Jacquard\'s loom cards — holes in stiff paper encoding fabric patterns — were repurposed by Hollerith and later IBM as the primary medium for programmable machine instruction.',
    effects: { data: 2 },
    tier: 2,
  },
  lovelace_algorithm: {
    id: 'lovelace_algorithm',
    name: 'Lovelace Algorithm',
    cluster: 'mechanical',
    x: -0.30,
    y: 0.44,
    description: 'Ada Lovelace\'s 1843 notes on Babbage\'s Analytical Engine include an algorithm for computing Bernoulli numbers — widely recognized as the first computer program ever written.',
    effects: { research: 4 },
    tier: 3,
  },
  steam_power: {
    id: 'steam_power',
    name: 'Steam Power',
    cluster: 'mechanical',
    x: -0.55,
    y: 0.22,
    description: 'Harnessing the expansive force of steam to drive pistons, flywheels, and ultimately the mechanical calculators that presaged the computer revolution.',
    effects: { energy: 2, production: 2 },
    tier: 1,
    isStarter: true,
    factionStarters: ['calculists'],
  },

  // --- CLUSTER: steampunk ---
  aetheric_engine: {
    id: 'aetheric_engine',
    name: 'Aetheric Engine',
    cluster: 'steampunk',
    x: -0.74,
    y: 0.40,
    description: 'A hypothetical device from the pages of Victorian scientific romance — an engine that channels the luminiferous aether itself as a medium for both computation and power.',
    effects: { energy: 3, compute: 3 },
    tier: 3,
  },
  clockwork_brain: {
    id: 'clockwork_brain',
    name: 'Clockwork Brain',
    cluster: 'steampunk',
    x: -0.65,
    y: 0.46,
    description: 'A fully mechanical brain of gears, cams, and escapements — imagined by Victorian engineers as the logical conclusion of Babbage\'s work, processing thoughts in brass and spring-steel.',
    effects: { compute: 4, research: 2 },
    tier: 3,
  },
  pneumatic_network: {
    id: 'pneumatic_network',
    name: 'Pneumatic Network',
    cluster: 'steampunk',
    x: -0.58,
    y: 0.52,
    description: 'A city-wide system of pressurized tubes carrying capsules of data, messages, and even small physical objects at speed — the Victorian internet.',
    effects: { data: 4 },
    tier: 3,
  },

  // --- CLUSTER: electrical ---
  electricity: {
    id: 'electricity',
    name: 'Electricity',
    cluster: 'electrical',
    x: 0.22,
    y: 0.12,
    description: 'Edison\'s direct-current grid and Tesla\'s alternating-current triumph — the mastery of electrical power that lit cities, drove motors, and made computation conceivable at scale.',
    effects: { energy: 3 },
    tier: 1,
    isStarter: true,
    factionStarters: ['electricians'],
  },
  telegraph: {
    id: 'telegraph',
    name: 'Telegraph',
    cluster: 'electrical',
    x: 0.35,
    y: 0.16,
    description: 'Morse\'s electromagnetic telegraph — the first technology to transmit information faster than a horse could carry it, shrinking continents and inaugurating the communication age.',
    effects: { data: 1, explore: 1 },
    tier: 1,
    isStarter: true,
    factionStarters: ['electricians'],
  },
  radio_wave: {
    id: 'radio_wave',
    name: 'Radio Wave',
    cluster: 'electrical',
    x: 0.45,
    y: 0.24,
    description: 'Hertz demonstrated electromagnetic waves; Marconi made them carry messages across oceans — wireless communication that freed information from the tyranny of copper wire.',
    effects: { data: 2, explore: 1 },
    tier: 2,
  },
  vacuum_tube: {
    id: 'vacuum_tube',
    name: 'Vacuum Tube',
    cluster: 'electrical',
    x: 0.30,
    y: 0.32,
    description: 'The thermionic valve — Lee de Forest\'s triode could amplify and switch electrical signals, making ENIAC\'s 18,000-tube brain and all early electronic computing possible.',
    effects: { compute: 2 },
    tier: 2,
    isStarter: true,
    factionStarters: ['retronaughts'],
  },
  logic_gate: {
    id: 'logic_gate',
    name: 'Logic Gate',
    cluster: 'electrical',
    x: 0.40,
    y: 0.38,
    description: 'Physical electronic implementations of Boolean AND, OR, and NOT — the atomic building blocks from which all digital circuits, from calculators to supercomputers, are composed.',
    effects: { compute: 2, research: 1 },
    tier: 3,
  },
  transistor: {
    id: 'transistor',
    name: 'Transistor',
    cluster: 'electrical',
    x: 0.55,
    y: 0.30,
    description: 'Shockley, Bardeen, and Brattain\'s semiconductor switch (1947) — smaller, faster, and cheaper than any vacuum tube, it is arguably the most important invention of the twentieth century.',
    effects: { compute: 3 },
    tier: 3,
  },
  integrated_circuit: {
    id: 'integrated_circuit',
    name: 'Integrated Circuit',
    cluster: 'electrical',
    x: 0.65,
    y: 0.40,
    description: 'Kilby and Noyce\'s revolutionary idea to etch millions of transistors onto a single silicon wafer — Moore\'s Law made flesh, compressing the history of computing onto a fingernail.',
    effects: { compute: 5 },
    tier: 4,
  },

  // --- CLUSTER: digital ---
  programming_language: {
    id: 'programming_language',
    name: 'Programming Language',
    cluster: 'digital',
    x: 0.42,
    y: 0.56,
    description: 'From Fortran to C to Python — human-readable languages that compile or interpret into machine code, letting programmers reason in concepts rather than bit patterns.',
    effects: { research: 4, compute: 2 },
    tier: 3,
  },
  ram_memory: {
    id: 'ram_memory',
    name: 'RAM Memory',
    cluster: 'digital',
    x: 0.55,
    y: 0.50,
    description: 'Random Access Memory — high-speed volatile storage that holds the active working state of any computation, making interactive and multitasking computing possible.',
    effects: { compute: 3, data: 2 },
    tier: 3,
  },
  hard_drive: {
    id: 'hard_drive',
    name: 'Hard Drive',
    cluster: 'digital',
    x: 0.68,
    y: 0.58,
    description: 'IBM\'s RAMAC (1956) introduced magnetic spinning platters for persistent mass storage — enabling databases, file systems, and the accumulation of institutional digital memory.',
    effects: { data: 5 },
    tier: 3,
  },
  operating_system: {
    id: 'operating_system',
    name: 'Operating System',
    cluster: 'digital',
    x: 0.60,
    y: 0.64,
    description: 'UNIX, CP/M, DOS, Windows — the master control program that manages hardware resources and provides a stable platform for all software to run on top of.',
    effects: { compute: 4, research: 3 },
    tier: 4,
  },
  microprocessor: {
    id: 'microprocessor',
    name: 'Microprocessor',
    cluster: 'digital',
    x: 0.75,
    y: 0.52,
    description: 'Intel\'s 4004 (1971) placed an entire CPU on a single chip — a complete programmable computer on a piece of silicon smaller than a fingernail, triggering the personal computing revolution.',
    effects: { compute: 7 },
    tier: 4,
  },
  personal_computer: {
    id: 'personal_computer',
    name: 'Personal Computer',
    cluster: 'digital',
    x: 0.82,
    y: 0.66,
    description: 'The Apple II, Commodore 64, and IBM PC brought computing to homes and classrooms — democratizing a tool that had been the exclusive domain of governments and corporations.',
    effects: { research: 5, data: 3 },
    tier: 5,
  },

  // --- CLUSTER: networked ---
  arpanet: {
    id: 'arpanet',
    name: 'ARPANET',
    cluster: 'networked',
    x: 0.08,
    y: 0.62,
    description: 'The Defense Department\'s experimental packet-switched network, first going online in 1969 — the technical and spiritual ancestor of the internet, proving that resilient distributed networks were possible.',
    effects: { data: 3, research: 2 },
    tier: 3,
    isStarter: true,
    factionStarters: ['cybernetix'],
  },
  encryption: {
    id: 'encryption',
    name: 'Encryption',
    cluster: 'networked',
    x: 0.22,
    y: 0.68,
    description: 'From Enigma machines to RSA public-key cryptography — the mathematics of securing information from adversaries, enabling private communication in a networked world.',
    effects: { military: 2, data: 2 },
    tier: 3,
  },
  internet: {
    id: 'internet',
    name: 'Internet',
    cluster: 'networked',
    x: 0.18,
    y: 0.76,
    description: 'The global network of networks, united by TCP/IP — a communication infrastructure that has become as essential to civilization as roads and electrical grids.',
    effects: { data: 6, research: 4 },
    tier: 4,
  },
  distributed_computing: {
    id: 'distributed_computing',
    name: 'Distributed Computing',
    cluster: 'networked',
    x: 0.35,
    y: 0.72,
    description: 'SETI@home, Folding@home, BitTorrent — the principle that many networked machines can collectively solve problems no single machine could, distributing both compute and resilience.',
    effects: { compute: 6, data: 4 },
    tier: 5,
  },
  world_wide_web: {
    id: 'world_wide_web',
    name: 'World Wide Web',
    cluster: 'networked',
    x: 0.45,
    y: 0.82,
    description: 'Tim Berners-Lee\'s hypertext system built atop the internet — HTML, HTTP, and URLs creating an interconnected web of documents that became the interface humanity uses to navigate information.',
    effects: { data: 8, research: 5 },
    tier: 5,
  },

  // --- CLUSTER: ai ---
  turing_test: {
    id: 'turing_test',
    name: 'Turing Test',
    cluster: 'ai',
    x: -0.35,
    y: 0.60,
    description: 'Turing\'s 1950 "imitation game" — his operational definition of machine intelligence as the ability to converse indistinguishably from a human, still debated seventy years later.',
    effects: { research: 3 },
    tier: 3,
  },
  perceptron: {
    id: 'perceptron',
    name: 'Perceptron',
    cluster: 'ai',
    x: -0.20,
    y: 0.68,
    description: 'Frank Rosenblatt\'s 1957 perceptron — a single-layer learning machine that could classify patterns, the first trainable neural network and the seed from which deep learning eventually grew.',
    effects: { research: 3, compute: 2 },
    tier: 3,
  },
  artificial_neural_network: {
    id: 'artificial_neural_network',
    name: 'Artificial Neural Network',
    cluster: 'ai',
    x: -0.08,
    y: 0.76,
    description: 'Networks of interconnected nodes modeled on biological neurons — given sufficient layers, data, and compute, they can learn to perceive, reason, and generate with superhuman precision.',
    effects: { research: 5, compute: 5 },
    tier: 4,
  },
  machine_learning: {
    id: 'machine_learning',
    name: 'Machine Learning',
    cluster: 'ai',
    x: 0.05,
    y: 0.84,
    description: 'The paradigm shift from hand-coded rules to learned statistical patterns — algorithms that improve at tasks by exposure to examples rather than explicit programming.',
    effects: { research: 6, compute: 4 },
    tier: 4,
    isStarter: true,
    factionStarters: ['neural'],
  },
  reinforcement_learning: {
    id: 'reinforcement_learning',
    name: 'Reinforcement Learning',
    cluster: 'ai',
    x: -0.15,
    y: 0.90,
    description: 'Learning through reward and punishment — the approach that let AlphaGo master Go, that trains robotic limbs to walk, and that gave AI systems emergent strategies no human designed.',
    effects: { military: 3, research: 5 },
    tier: 5,
  },
  deep_learning: {
    id: 'deep_learning',
    name: 'Deep Learning',
    cluster: 'ai',
    x: -0.25,
    y: 0.82,
    description: 'Many-layered neural networks trained end-to-end on massive datasets — the technical revolution behind image recognition, translation, voice synthesis, and generative AI.',
    effects: { research: 8, compute: 8 },
    tier: 5,
  },
  large_language_model: {
    id: 'large_language_model',
    name: 'Large Language Model',
    cluster: 'ai',
    x: -0.05,
    y: 0.94,
    description: 'Transformer-based models trained on the bulk of human text output — systems that can write, summarize, translate, code, and reason with startling fluency across almost any domain.',
    effects: { research: 10, data: 8 },
    tier: 6,
  },
  agi: {
    id: 'agi',
    name: 'Artificial General Intelligence',
    cluster: 'ai',
    x: -0.30,
    y: 1.00,
    description: 'A system matching or exceeding human cognitive ability across all domains — the threshold beyond which the pace of progress may become impossible to predict or control.',
    effects: { research: 15, compute: 15, military: 10 },
    tier: 7,
    winCondition: true,
  },

  // --- CLUSTER: quantum ---
  quantum_mechanics: {
    id: 'quantum_mechanics',
    name: 'Quantum Mechanics',
    cluster: 'quantum',
    x: -0.88,
    y: 0.58,
    description: 'Planck, Heisenberg, Schrödinger, and Bohr\'s revolutionary framework — the physics of superposition, entanglement, and uncertainty that governs the behavior of atoms and photons.',
    effects: { research: 4 },
    tier: 3,
  },
  quantum_computing: {
    id: 'quantum_computing',
    name: 'Quantum Computing',
    cluster: 'quantum',
    x: -0.75,
    y: 0.72,
    description: 'Harnessing superposition and entanglement to represent and manipulate information as qubits — enabling exponential speedup over classical computers for specific problem classes.',
    effects: { compute: 12, research: 8 },
    tier: 5,
  },
  quantum_supremacy: {
    id: 'quantum_supremacy',
    name: 'Quantum Supremacy',
    cluster: 'quantum',
    x: -0.65,
    y: 0.84,
    description: 'Google\'s Sycamore processor (2019) solved in 200 seconds a problem estimated to take the world\'s fastest classical supercomputer 10,000 years — the first credible quantum supremacy claim.',
    effects: { compute: 20, research: 12 },
    tier: 6,
  },
  consciousness_upload: {
    id: 'consciousness_upload',
    name: 'Consciousness Upload',
    cluster: 'quantum',
    x: -0.58,
    y: 0.95,
    description: 'The theoretical transfer of a human mind to a digital substrate — requiring a complete map of neural connectivity and quantum-coherent simulation of biological cognition.',
    effects: { research: 20, military: 15 },
    tier: 7,
    winCondition: true,
  },
};

// ---------------------------------------------------------------------------
// COMBINATIONS
// ---------------------------------------------------------------------------
const COMBINATIONS = [
  // Mythological tier
  {
    ingredients: ['bronze_automaton', 'greek_clockwork'],
    result: 'antikythera_mind',
    researchCost: 10,
    newConcept: {
      id: 'antikythera_mind',
      name: 'Antikythera Mind',
      cluster: 'mythological',
      x: -0.72,
      y: 0.20,
      description: 'A thinking mechanical device inspired by the Antikythera mechanism — part clockwork oracle, part bronze brain, computing the movements of stars and the fates of civilizations.',
      effects: { compute: 3, research: 2 },
      tier: 3,
    },
  },
  {
    ingredients: ['wooden_bird', 'steam_power'],
    result: 'steam_automaton',
    researchCost: 15,
    newConcept: {
      id: 'steam_automaton',
      name: 'Steam Automaton',
      cluster: 'steampunk',
      x: -0.78,
      y: 0.36,
      description: 'Steam-powered mechanical bird, half myth half machine — an ancient dream of flight married to Victorian industrial power, soaring on jets of pressurized water vapor.',
      effects: { military: 3, production: 2 },
      tier: 3,
    },
  },
  {
    ingredients: ['golden_maiden', 'machine_learning'],
    result: 'digital_spirit',
    researchCost: 40,
    newConcept: {
      id: 'digital_spirit',
      name: 'Digital Spirit',
      cluster: 'ai',
      x: -0.42,
      y: 0.78,
      description: 'An AI that has internalized the archetype of divine crafted servants — it does not merely execute instructions but pursues purpose, echoing Hephaestus\'s golden maidens across ten millennia.',
      effects: { research: 6, military: 4 },
      tier: 5,
    },
  },
  {
    ingredients: ['bronze_automaton', 'electricity'],
    result: 'electric_golem',
    researchCost: 20,
    newConcept: {
      id: 'electric_golem',
      name: 'Electric Golem',
      cluster: 'electrical',
      x: 0.28,
      y: 0.26,
      description: 'An ancient bronze form animated by modern electricity — galvanized muscles of corroded metal lurching to life under high voltage, a Frankenstein of mythological engineering.',
      effects: { military: 4, energy: 2 },
      tier: 3,
    },
  },

  // Mathematical tier
  {
    ingredients: ['binary_system', 'boolean_logic'],
    result: 'formal_logic',
    researchCost: 8,
  },
  {
    ingredients: ['formal_logic', 'calculus'],
    result: 'information_theory',
    researchCost: 20,
  },
  {
    ingredients: ['information_theory', 'turing_completeness'],
    result: 'quantum_mechanics',
    researchCost: 30,
  },
  {
    ingredients: ['universal_characteristic', 'internet'],
    result: 'semantic_web',
    researchCost: 40,
    newConcept: {
      id: 'semantic_web',
      name: 'Semantic Web',
      cluster: 'networked',
      x: 0.22,
      y: 0.78,
      description: 'Leibniz\'s dream of a universal language of thought realized as machine-readable meaning across the web — ontologies, RDF, and linked data weaving the internet into a reasoning engine.',
      effects: { data: 6, research: 5 },
      tier: 5,
    },
  },
  {
    ingredients: ['boolean_logic', 'electricity'],
    result: 'vacuum_tube',
    researchCost: 12,
  },
  {
    ingredients: ['binary_system', 'punch_card'],
    result: 'lovelace_algorithm',
    researchCost: 15,
  },
  {
    ingredients: ['formal_logic', 'programming_language'],
    result: 'turing_completeness',
    researchCost: 25,
  },

  // Mechanical tier
  {
    ingredients: ['leibniz_wheel', 'steam_power'],
    result: 'difference_engine',
    researchCost: 15,
  },
  {
    ingredients: ['difference_engine', 'lovelace_algorithm'],
    result: 'analytical_engine',
    researchCost: 20,
  },
  {
    ingredients: ['steam_power', 'difference_engine'],
    result: 'aetheric_engine',
    researchCost: 18,
  },
  {
    ingredients: ['aetheric_engine', 'binary_system'],
    result: 'clockwork_brain',
    researchCost: 20,
  },
  {
    ingredients: ['clockwork_brain', 'pneumatic_network'],
    result: 'analytical_engine',
    researchCost: 20,
  },
  {
    ingredients: ['punch_card', 'analytical_engine'],
    result: 'programming_language',
    researchCost: 22,
  },
  {
    ingredients: ['steam_power', 'bronze_automaton'],
    result: 'steam_automaton',
    researchCost: 15,
  },
  {
    ingredients: ['hero_pneumatics', 'binary_system'],
    result: 'pneumatic_network',
    researchCost: 15,
  },

  // Electrical tier
  {
    ingredients: ['electricity', 'telegraph'],
    result: 'radio_wave',
    researchCost: 10,
  },
  {
    ingredients: ['vacuum_tube', 'binary_system'],
    result: 'logic_gate',
    researchCost: 15,
  },
  {
    ingredients: ['logic_gate', 'transistor'],
    result: 'integrated_circuit',
    researchCost: 25,
  },
  {
    ingredients: ['transistor', 'programming_language'],
    result: 'microprocessor',
    researchCost: 28,
  },
  {
    ingredients: ['integrated_circuit', 'programming_language'],
    result: 'microprocessor',
    researchCost: 30,
  },
  {
    ingredients: ['integrated_circuit', 'ram_memory'],
    result: 'hard_drive',
    researchCost: 25,
  },
  {
    ingredients: ['transistor', 'binary_system'],
    result: 'ram_memory',
    researchCost: 18,
  },
  {
    ingredients: ['radio_wave', 'transistor'],
    result: 'arpanet',
    researchCost: 20,
  },

  // Digital tier
  {
    ingredients: ['microprocessor', 'ram_memory'],
    result: 'operating_system',
    researchCost: 28,
  },
  {
    ingredients: ['operating_system', 'hard_drive'],
    result: 'personal_computer',
    researchCost: 30,
  },
  {
    ingredients: ['personal_computer', 'arpanet'],
    result: 'distributed_computing',
    researchCost: 32,
  },
  {
    ingredients: ['arpanet', 'encryption'],
    result: 'internet',
    researchCost: 25,
  },
  {
    ingredients: ['internet', 'distributed_computing'],
    result: 'world_wide_web',
    researchCost: 35,
  },

  // AI tier
  {
    ingredients: ['turing_completeness', 'formal_logic'],
    result: 'turing_test',
    researchCost: 25,
  },
  {
    ingredients: ['information_theory', 'calculus'],
    result: 'perceptron',
    researchCost: 22,
  },
  {
    ingredients: ['perceptron', 'programming_language'],
    result: 'artificial_neural_network',
    researchCost: 28,
  },
  {
    ingredients: ['artificial_neural_network', 'distributed_computing'],
    result: 'machine_learning',
    researchCost: 32,
  },
  {
    ingredients: ['machine_learning', 'microprocessor'],
    result: 'deep_learning',
    researchCost: 40,
  },
  {
    ingredients: ['deep_learning', 'reinforcement_learning'],
    result: 'large_language_model',
    researchCost: 50,
  },
  {
    ingredients: ['large_language_model', 'quantum_computing'],
    result: 'agi',
    researchCost: 80,
  },
  {
    ingredients: ['turing_test', 'machine_learning'],
    result: 'reinforcement_learning',
    researchCost: 35,
  },

  // Quantum tier
  {
    ingredients: ['quantum_mechanics', 'integrated_circuit'],
    result: 'quantum_computing',
    researchCost: 45,
  },
  {
    ingredients: ['quantum_computing', 'deep_learning'],
    result: 'quantum_supremacy',
    researchCost: 60,
  },
  {
    ingredients: ['quantum_supremacy', 'artificial_neural_network'],
    result: 'consciousness_upload',
    researchCost: 75,
  },

  // Cross-cluster interesting combos
  {
    ingredients: ['clockwork_brain', 'turing_test'],
    result: 'clockwork_turing',
    researchCost: 30,
    newConcept: {
      id: 'clockwork_turing',
      name: 'Clockwork Turing',
      cluster: 'steampunk',
      x: -0.62,
      y: 0.52,
      description: 'A Victorian machine that passes the Turing Test through pure mechanical ingenuity — gears simulating grammar, cams encoding context, springs springing to conversational life.',
      effects: { compute: 5, research: 4 },
      tier: 4,
    },
  },
  {
    ingredients: ['aetheric_engine', 'radio_wave'],
    result: 'pneumatic_network',
    researchCost: 20,
  },
  {
    ingredients: ['greek_clockwork', 'programming_language'],
    result: 'lovelace_algorithm',
    researchCost: 18,
  },
  {
    ingredients: ['fire_bull', 'electricity'],
    result: 'electric_golem',
    researchCost: 20,
  },
  {
    ingredients: ['hero_pneumatics', 'electricity'],
    result: 'vacuum_tube',
    researchCost: 12,
  },
  {
    ingredients: ['wooden_bird', 'arpanet'],
    result: 'distributed_computing',
    researchCost: 30,
  },
  {
    ingredients: ['encryption', 'quantum_computing'],
    result: 'quantum_supremacy',
    researchCost: 55,
  },
  {
    ingredients: ['golden_maiden', 'operating_system'],
    result: 'digital_spirit',
    researchCost: 38,
  },
];

// ---------------------------------------------------------------------------
// EVENTS
// ---------------------------------------------------------------------------
const EVENTS = [
  {
    id: 'solar_flare',
    name: 'Solar Flare',
    type: 'disaster',
    description: 'A massive coronal ejection bombards the planet with charged particles, frying unshielded power infrastructure and forcing a scramble to restore energy grids.',
    effect: { energy_mult: 0.5, duration: 3 },
    icon: '☀️',
    probability: 0.06,
  },
  {
    id: 'data_windfall',
    name: 'Data Windfall',
    type: 'windfall',
    description: 'A cache of ancient server archives is uncovered, flooding every civilization with vast troves of unprocessed but enormously valuable data.',
    effect: { data: 20 },
    icon: '💾',
    probability: 0.08,
  },
  {
    id: 'silicon_rush',
    name: 'Silicon Rush',
    type: 'windfall',
    description: 'Geologists announce a massive new silicon deposit spanning multiple regions, triggering a production boom as mines go into overdrive.',
    effect: { silicon_mult: 2, duration: 5 },
    icon: '💎',
    probability: 0.07,
  },
  {
    id: 'quantum_storm',
    name: 'Quantum Storm',
    type: 'disaster',
    description: 'An anomalous quantum decoherence wave sweeps the planet, collapsing qubits and taking all quantum-dependent buildings offline until conditions stabilize.',
    effect: { quantum_disabled: true, duration: 2 },
    icon: '🌀',
    probability: 0.05,
  },
  {
    id: 'ai_breakthrough',
    name: 'AI Breakthrough',
    type: 'windfall',
    description: 'A randomly selected civilization\'s researchers achieve an unexpected breakthrough, discovering a tier-3 concept without the usual prerequisites.',
    effect: { random_concept: true, tier: 3 },
    icon: '🤖',
    probability: 0.07,
  },
  {
    id: 'logic_virus',
    name: 'Logic Virus',
    type: 'disaster',
    description: 'A self-replicating malicious program spreads through networked infrastructure, corrupting control systems and destroying one building in each civilization before containment.',
    effect: { destroy_building: true },
    icon: '🦠',
    probability: 0.05,
  },
  {
    id: 'computational_renaissance',
    name: 'Computational Renaissance',
    type: 'windfall',
    description: 'A global surge of intellectual energy sweeps through academic and research communities, halving the cost of all concept research for several turns.',
    effect: { research_cost_mult: 0.5, duration: 5 },
    icon: '🎨',
    probability: 0.06,
  },
  {
    id: 'energy_crisis',
    name: 'Energy Crisis',
    type: 'disaster',
    description: 'A cascading failure in the global energy supply chain halts all energy production, forcing civilizations to run on reserves until the crisis resolves.',
    effect: { energy_mult: 0, duration: 2 },
    icon: '🔌',
    probability: 0.04,
  },
  {
    id: 'ancient_discovery',
    name: 'Ancient Discovery',
    type: 'windfall',
    description: 'Archaeologists unearth artifacts of a prior technological civilization, gifting all factions with one free tier-1 concept from their cultural heritage.',
    effect: { tier1_concept: true },
    icon: '🏺',
    probability: 0.07,
  },
  {
    id: 'network_cascade',
    name: 'Network Cascade',
    type: 'disaster',
    description: 'A botnet-driven cascade overwhelms global routing infrastructure, throttling data building output across all civilizations for several turns.',
    effect: { data_mult: 0.5, duration: 3 },
    icon: '📡',
    probability: 0.06,
  },
  {
    id: 'rare_earth_bonanza',
    name: 'Rare Earth Bonanza',
    type: 'windfall',
    description: 'Deep-sea mining expeditions return with enormous hauls of rare earth elements, distributing five units of rare earth to every civilization on the map.',
    effect: { rareEarth: 5 },
    icon: '⛏️',
    probability: 0.08,
  },
  {
    id: 'cooling_breakthrough',
    name: 'Cooling Breakthrough',
    type: 'windfall',
    description: 'A materials science breakthrough yields room-temperature superconducting coolants, eliminating heat penalties across all terrain types for an extended period.',
    effect: { no_heat: true, duration: 10 },
    icon: '❄️',
    probability: 0.06,
  },
  {
    id: 'emp_pulse',
    name: 'EMP Pulse',
    type: 'disaster',
    description: 'A high-altitude electromagnetic pulse detonation — origin unknown — fries unshielded electronics, dealing damage to all deployed units across the map.',
    effect: { unit_damage: 2, duration: 1 },
    icon: '💥',
    probability: 0.05,
  },
  {
    id: 'great_minds',
    name: 'Great Minds',
    type: 'windfall',
    description: 'A generation of exceptional intellects emerges simultaneously across civilizations, each contributing landmark insights that boost every faction\'s research stockpile.',
    effect: { research: 15 },
    icon: '🧑‍🔬',
    probability: 0.08,
  },
];

// ---------------------------------------------------------------------------
// UNIT TYPES
// ---------------------------------------------------------------------------
const UNIT_TYPES = {
  scout: {
    id: 'scout',
    name: 'Scout',
    icon: '🔭',
    attack: 1,
    defense: 1,
    movement: 3,
    cost: { silicon: 1, energy: 1 },
    description: 'Fast-moving reconnaissance unit optimized for map exploration and intelligence gathering rather than direct combat.',
  },
  warrior: {
    id: 'warrior',
    name: 'Warrior',
    icon: '⚔️',
    attack: 3,
    defense: 2,
    movement: 2,
    cost: { silicon: 2, energy: 2 },
    description: 'Standard combat unit — the workhorse of any military, balancing offensive power with reasonable defensive capability and mobility.',
  },
  siege: {
    id: 'siege',
    name: 'Siege Engine',
    icon: '🏹',
    attack: 8,
    defense: 1,
    movement: 1,
    cost: { silicon: 4, copper: 2, energy: 3 },
    description: 'Heavy artillery unit with devastating offensive power against fortifications and buildings, but slow and nearly defenseless against mobile attackers.',
  },
  cyber_warrior: {
    id: 'cyber_warrior',
    name: 'Cyber Warrior',
    icon: '🤺',
    attack: 5,
    defense: 4,
    movement: 2,
    cost: { silicon: 3, rareEarth: 1, energy: 3 },
    requires: ['integrated_circuit'],
    description: 'An elite soldier augmented with cybernetic implants and networked tactical systems, capable in both conventional combat and electronic warfare.',
  },
  quantum_agent: {
    id: 'quantum_agent',
    name: 'Quantum Agent',
    icon: '👾',
    attack: 12,
    defense: 8,
    movement: 3,
    cost: { quantum: 2, silicon: 5, energy: 8 },
    requires: ['quantum_computing'],
    description: 'The apex military unit — a quantum-enhanced operative whose probabilistic sensors and encryption-breaking capabilities make them nearly unstoppable.',
  },
};

// ---------------------------------------------------------------------------
// CLUSTER METADATA
// ---------------------------------------------------------------------------
const CLUSTER_META = {
  mythological: {
    color: '#C9A84C',
    label: 'Mythological',
    description: 'Ancient automata, divine machines, and the first imaginings of artificial life — from Hephaestus\'s forge to the workshops of Chinese legend.',
  },
  mathematical: {
    color: '#8855CC',
    label: 'Mathematical',
    description: 'The formal foundations of computation: logic, algebra, information theory, and the abstract machines that underlie all digital thought.',
  },
  mechanical: {
    color: '#8B6914',
    label: 'Mechanical',
    description: 'Gears, wheels, punch cards, and difference engines — the long march from abacus to Analytical Engine through brass and clockwork.',
  },
  steampunk: {
    color: '#B8621A',
    label: 'Steampunk',
    description: 'Victorian visions of computation taken to their logical extreme — pneumatic networks, clockwork brains, and aetheric engines wreathed in steam.',
  },
  electrical: {
    color: '#FFA040',
    label: 'Electrical',
    description: 'From Edison\'s first bulb to the transistor revolution — harnessing electrons to switch, amplify, and ultimately think.',
  },
  digital: {
    color: '#00CC44',
    label: 'Digital',
    description: 'The age of silicon chips, operating systems, and personal computers — when computation left the mainframe and entered daily life.',
  },
  networked: {
    color: '#3399FF',
    label: 'Networked',
    description: 'ARPANET, encryption, the internet, and the web — computation as communication infrastructure, binding civilizations into a single data organism.',
  },
  ai: {
    color: '#00CCCC',
    label: 'Artificial Intelligence',
    description: 'From the Turing test to AGI — the long project of teaching machines to perceive, reason, learn, and ultimately surpass their creators.',
  },
  quantum: {
    color: '#CC00CC',
    label: 'Quantum',
    description: 'Superposition, entanglement, and qubits — the frontier where physics and computation merge, promising exponential power and uploading minds to silicon.',
  },
};

// ─── RESEARCH BRANCHES ────────────────────────────────────────────────────────
// Each concept belongs to one branch. Proficiency in a branch (0–10) affects
// combination success rate and cost for combos involving concepts from that branch.

const RESEARCH_BRANCHES = {
  archaeotech: {
    id: 'archaeotech',
    label: 'Archaeotech',
    color: '#C9A84C',
    description: 'Ancient mechanical traditions — automata, clockwork, steam',
    clusters: ['mythological', 'steampunk'],
    icon: '⚙️',
  },
  logic: {
    id: 'logic',
    label: 'Logic & Mathematics',
    color: '#9B59B6',
    description: 'Formal reasoning, binary systems, information theory',
    clusters: ['mathematical'],
    icon: '∑',
  },
  engineering: {
    id: 'engineering',
    label: 'Engineering',
    color: '#E67E22',
    description: 'Physical construction — mechanical, electrical, circuits',
    clusters: ['mechanical', 'electrical'],
    icon: '🔧',
  },
  computation: {
    id: 'computation',
    label: 'Computation',
    color: '#2ECC71',
    description: 'Digital systems — processors, memory, operating systems',
    clusters: ['digital'],
    icon: '💻',
  },
  networks: {
    id: 'networks',
    label: 'Networks',
    color: '#3498DB',
    description: 'Connected systems — protocols, internet, distributed computing',
    clusters: ['networked'],
    icon: '🌐',
  },
  cognitive: {
    id: 'cognitive',
    label: 'Cognitive Science',
    color: '#00BCD4',
    description: 'Intelligence and learning — neural networks, ML, AI',
    clusters: ['ai'],
    icon: '🧠',
  },
  quantum: {
    id: 'quantum',
    label: 'Quantum Theory',
    color: '#E91E63',
    description: 'Quantum mechanics and quantum computing',
    clusters: ['quantum'],
    icon: '⚛️',
  },
};

// Distance matrix between branches (1=adjacent, 2=moderate, 3=far, 4=very far).
// Higher distance = bigger penalty when cross-combining without proficiency.
const BRANCH_DISTANCES = {
  archaeotech: { archaeotech:0, logic:2, engineering:2, computation:3, networks:4, cognitive:4, quantum:4 },
  logic:       { archaeotech:2, logic:0, engineering:1, computation:2, networks:2, cognitive:2, quantum:2 },
  engineering: { archaeotech:2, logic:1, engineering:0, computation:1, networks:2, cognitive:3, quantum:3 },
  computation: { archaeotech:3, logic:2, engineering:1, computation:0, networks:1, cognitive:2, quantum:3 },
  networks:    { archaeotech:4, logic:2, engineering:2, computation:1, networks:0, cognitive:1, quantum:2 },
  cognitive:   { archaeotech:4, logic:2, engineering:3, computation:2, networks:1, cognitive:0, quantum:2 },
  quantum:     { archaeotech:4, logic:2, engineering:3, computation:3, networks:2, cognitive:2, quantum:0 },
};

// Maps each concept cluster to its research branch
const CLUSTER_TO_BRANCH = {
  mythological: 'archaeotech',
  steampunk:    'archaeotech',
  mathematical: 'logic',
  mechanical:   'engineering',
  electrical:   'engineering',
  digital:      'computation',
  networked:    'networks',
  ai:           'cognitive',
  quantum:      'quantum',
};

// Starting branch proficiency per faction (0-10 scale).
// This simulates how "natural" each tradition finds different research directions.
// Branching into a 0-proficiency branch from a distance-4 branch is very hard.
const FACTION_BRANCH_PROFICIENCY = {
  ancients:     { archaeotech:5, logic:1, engineering:2, computation:0, networks:0, cognitive:0, quantum:0 },
  calculists:   { archaeotech:2, logic:5, engineering:3, computation:1, networks:0, cognitive:1, quantum:0 },
  electricians: { archaeotech:1, logic:1, engineering:5, computation:2, networks:1, cognitive:0, quantum:0 },
  retronaughts: { archaeotech:0, logic:2, engineering:3, computation:5, networks:2, cognitive:1, quantum:0 },
  cybernetix:   { archaeotech:0, logic:1, engineering:2, computation:3, networks:5, cognitive:2, quantum:0 },
  neural:       { archaeotech:0, logic:2, engineering:1, computation:3, networks:2, cognitive:5, quantum:1 },
  dystopians:   { archaeotech:0, logic:1, engineering:2, computation:3, networks:3, cognitive:2, quantum:1 },
  utopians:     { archaeotech:1, logic:2, engineering:1, computation:2, networks:3, cognitive:5, quantum:2 },
};

// Research buildings that boost specific branch proficiency.
// These extend the BUILDINGS const (engine.js will merge them in).
const BRANCH_RESEARCH_BUILDINGS = {
  archaeotech_workshop: {
    id: 'archaeotech_workshop', name: 'Archaeotech Workshop', icon: '⚙️',
    cost: { silicon:2, copper:2, energy:2 },
    production: { research:2 },
    branchBoost: { branch:'archaeotech', amount:1 },
    description: 'Trains engineers in ancient mechanical traditions (+1 Archaeotech proficiency)',
    tier: 1,
  },
  logic_institute: {
    id: 'logic_institute', name: 'Logic Institute', icon: '∑',
    cost: { silicon:2, energy:2 },
    production: { research:3 },
    branchBoost: { branch:'logic', amount:1 },
    description: 'Formalizes mathematical reasoning traditions (+1 Logic proficiency)',
    tier: 1,
  },
  engineering_guild: {
    id: 'engineering_guild', name: 'Engineering Guild', icon: '🔧',
    cost: { copper:3, energy:2 },
    production: { research:2, silicon:1 },
    branchBoost: { branch:'engineering', amount:1 },
    description: 'Coordinates physical construction expertise (+1 Engineering proficiency)',
    tier: 1,
  },
  computation_center: {
    id: 'computation_center', name: 'Computation Center', icon: '💻',
    cost: { silicon:4, energy:3 },
    production: { research:3, compute:1 },
    branchBoost: { branch:'computation', amount:1 },
    description: 'Centralizes digital computing research (+1 Computation proficiency)',
    tier: 2,
    requires: ['vacuum_tube'],
  },
  network_hub: {
    id: 'network_hub', name: 'Network Hub', icon: '🌐',
    cost: { copper:3, silicon:2, energy:3 },
    production: { research:2, data:2 },
    branchBoost: { branch:'networks', amount:1 },
    description: 'Connects distributed research nodes (+1 Networks proficiency)',
    tier: 2,
    requires: ['telegraph'],
  },
  cognitive_lab: {
    id: 'cognitive_lab', name: 'Cognitive Lab', icon: '🧠',
    cost: { silicon:4, rareEarth:1, energy:4 },
    production: { research:4, compute:1 },
    branchBoost: { branch:'cognitive', amount:1 },
    description: 'Studies intelligence and machine learning (+1 Cognitive proficiency)',
    tier: 2,
    requires: ['turing_test'],
  },
  quantum_observatory: {
    id: 'quantum_observatory', name: 'Quantum Observatory', icon: '⚛️',
    cost: { quantum:1, rareEarth:2, energy:5 },
    production: { research:4, quantum:1 },
    branchBoost: { branch:'quantum', amount:1 },
    description: 'Explores quantum phenomena (+1 Quantum proficiency)',
    tier: 3,
    requires: ['quantum_mechanics'],
  },
  // Cross-branch "translation" buildings that bridge distant traditions
  translation_engine: {
    id: 'translation_engine', name: 'Translation Engine', icon: '🔄',
    cost: { rareEarth:2, silicon:3, energy:4 },
    production: { research:3 },
    branchBoost: { branch:'all', amount:0.5 }, // +0.5 to ALL branches
    description: 'Finds equivalences between disparate technological traditions (+0.5 all branches)',
    tier: 2,
    requires: ['formal_logic'],
  },
};

// Combination success formula (exported for engine.js):
// baseSuccess = 0.60
// profBonus = (profA + profB) * 0.04  (each point of proficiency = +4%)
// distancePenalty = branchDistance * 0.08  (per unit of distance = -8%)
// finalChance = clamp(baseSuccess + profBonus - distancePenalty, 0.10, 1.00)
// Cost reduction = (avgProficiency / 10) * 0.60  (up to 60% off at max proficiency)
const COMBO_FORMULA = {
  baseSuccessChance: 0.60,
  proficiencyBonusPerPoint: 0.04,  // per proficiency level in each relevant branch
  distancePenaltyPerUnit: 0.08,    // per unit of BRANCH_DISTANCES between the two concepts
  minSuccessChance: 0.10,
  maxSuccessChance: 1.00,
  maxCostReduction: 0.60,          // at proficiency 10 in both branches, costs 60% less
};
